### ISSUE TITLE
帖子编辑页面无法上传图片

### ISSUE THREAD

**Issue by qinxiaozhi** [freedom10086/Ruisi#2]
2018年新年快乐~
祝各位开发者大大在新的一年里心想事成，万事如意哈~

顺便报两个BUG，
1. activity/EditActivity.java文件中未实现点击图片上传按钮上传图片的逻辑，因此在编辑帖子时无法上传图片
2. 编辑帖子的form的delete属性可能为真，点击编辑完成就会删帖

问题2的修复方法：
在activity.EditActivity#startPost方法中
```java
        params.put("subject", edTitle.getText().toString());
        params.put("message", edContent.getText().toString());
```
两句下方加入
```java
        params.remove("delete");
```
就好~

**Comment by freedom10086** [comment]
2018年新年快乐~ 感谢反馈
- 关于1 完全是我懒。。。，应该把发帖和编辑放在一个Activity的，导致我不想把重复的代码写2遍
- 关于2 感谢反馈此问题， 什么情况下会出现次情况呢？

**Comment by qinxiaozhi** [comment]
咦咦咦。。。啥时候QQ邮箱自动把GitHub的邮件自动收进垃圾箱了？

问题1现在我的解决方案是抄了一遍。。实际上感觉这个完全可以抽出来专门开个项目，弄个BBcode的安卓富文本输入器，问题2请看这里：

https://gitee.com/ComsenzDiscuz/DiscuzX/blob/master/upload/template/default/mobile/forum/post.htm#L142

源代码中删除帖子的checkbox`<input type="checkbox" name="delete" id="delete" class="pc" value="1" `默认值为1，而在您的项目中 https://github.com/freedom10086/Ruisi/blob/master/app/src/main/java/me/yluo/ruisiapp/activity/EditActivity.java#L142 处直接从HTML中解析得到params，于是乎delete=1的值也就被加入到params了，然后用户编辑完成提交修改，BOOM

**Comment by qinxiaozhi** [comment]
问题二的情况我不知道您那为啥没有发生。。或许是版本问题？😅

**Comment by qinxiaozhi** [comment]
另外，不知道您有兴趣大改没有，我的网站想用 知道白手机模板，然而您的项目和手机版前端耦合，emmmm，discuz论坛有提供手机Json api，比前端解析要稳定得多

**Comment by qinxiaozhi** [comment]
另外不知道欢不欢迎pull request，我已经把论坛版块列表那做了些增强，从forum.json换到api接口动态获取，版块下子版块可通过点击标题进入等，不知道对这个项目的发展有用没用23333

**Comment by freedom10086** [comment]
抱歉今天才看到
有json api再好不过了，我这是没有api才出的如此下下策。。。解析前端。pull request当然是支持的。dz的Json Api需要单独开启吧？bbcode富文本确实需要不过工作量估计能开一个项目了。

**Comment by qinxiaozhi** [comment]
嗯，好的，dz的jsonapi不需要单独开启，从这里便可以访问:http://rsbbs.xidian.edu.cn/api/mobile/?check
bbcode编辑器的富文本化我做了些尝试，感觉hold不住，不过我做了些小修改让编辑页面的使用方式和电脑前端差不多一致，这两天有空我提交过来

**Comment by KingsFish** [comment]
已解决
