### ISSUE TITLE
校园网环境下信息有误

### ISSUE THREAD

**Issue by KingsFish** [freedom10086/Ruisi#4]
![1](https://user-images.githubusercontent.com/12454995/37071207-5cb72e7a-21f6-11e8-8f07-ad2ca94cb88e.png)

***

`APP`版本：`2.8.0`
`Andorid`版本：`7.1.2`

如图，校园网环境下会出现信息位置不对的bug

包括四个部分
- 作者
- 时间
- 浏览人数
- 回复数

猜测可能在初始化`RecyclerView`条目数据时`TextView`的`id`弄错了

**Comment by freedom10086** [comment]
这个问题一直存在吗？应该是网络类型判断有误
我现在看就是好的

**Comment by freedom10086** [comment]
还有吗？ 看来我要好好找找问题了 
移动网络直接判断为外网，其余通过一个HTTP请求，校园网又返回认为是校园网

**Comment by KingsFish** [comment]
是的呢。。。

对了。你应该有几个账号吧。切换账号试一下看能不能复现
