### ISSUE TITLE
最近手机浏览器直接访问睿思没有响应

### ISSUE THREAD

**Issue by darkgirl** [freedom10086/Ruisi#6]
不知道为什么我手机安装睿思apk的时候显示包解析错误，所以一般情况我都是用手机浏览器直接访问的，可是一个多星期前移动网络突然不能访问http://rsbbs.xidian.edu.cn了是什么情况呀，但是访问西电开源http://linux.xidian.edu.cn和西电acm http://rsbbs.xidian.edu.cn却是正常的

**Comment by tamarous** [comment]
因为最近是敏感时期，所以学校把睿思的外网访问权限给关掉了，开完会应该就恢复了 @darkgirl

**Comment by freedom10086** [comment]
包解析错误适应为Android版本不行？应用最低支持Android 5.0。
关于不能访问楼上已经说了，好像20号之后学校会开放外网访问。

**Comment by freedom10086** [comment]
已经恢复正常 外网可以访问了
